// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tssyibamgcgqqjjmrcks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzc3lpYmFtZ2NncXFqam1yY2tzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMDc3ODUsImV4cCI6MjA2MjY4Mzc4NX0.RQZzwbkCWU8AnlG4mR8FYSOvCLne9RjxC43XPZIHRtE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);